stages:
  - build

before_script:
  -  docker login -u $CI_REGISTRY_USER -p $CI_BUILD_TOKEN $CI_REGISTRY

docker:
  stage: build
  only:
    - "client-demo"
  variables:
    TAG: "20.07"
  script:
    - docker build --rm --no-cache -t ${CI_REGISTRY_IMAGE}:export-$TAG --build-arg tag=${TAG} -f docker/Dockerfile.export .
    - docker build --rm --no-cache -t ${CI_REGISTRY_IMAGE}:client-$TAG --build-arg tag=${TAG} -f docker/Dockerfile.client .
    - docker pull nvcr.io/nvidia/tritonserver:${TAG}-py3
    - docker tag nvcr.io/nvidia/tritonserver:${TAG}-py3 ${CI_REGISTRY_IMAGE}:server-${TAG}
    - docker push ${CI_REGISTRY_IMAGE}:export-${TAG}
    - docker push ${CI_REGISTRY_IMAGE}:client-${TAG}
    - docker push ${CI_REGISTRY_IMAGE}:server-${TAG}
